spring.application.name=bookstore

# Configuração do Banco Local
spring.datasource.url=jdbc:postgresql://localhost:5432/bookstore-api
spring.datasource.username=postgres
spring.datasource.password=0000

# Cria tabelas, colunas, constraints, etc, automaticamente com o mapeamento das entidades
spring.jpa.hibernate.ddl-auto=update

# Remove Logs de erro de metadados
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

## Exibe o SQL Gerado no console
spring.jpa.show-sql=true
